config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations', :passwords => "passwords" }
  # get 'hello_world', to: 'hello_world#index'
  root 'home#index'
  resources :events do
    resources :ads
  end
  scope :auth do
    get 'is_signed_in', to: 'auth#is_signed_in?'
  end
end

app/models/ad.rb
class Ad < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  belongs_to :event
  belongs_to :user
  validates :title, :description, :user_id, :start_date, :termination_date, presence: true
  has_attached_file :file, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing_2.png'
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
  geocoded_by :address # can also be an IP address
  after_validation :geocode, if: ->(obj) { obj.address.present? && obj.address_changed? }
  belongs_to :user
  has_many :ads
  validates :title, :description, :user_id, :start_date, :termination_date, presence: true
  has_attached_file :file, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing_2.png'
  validates_attachment_content_type :file, content_type: /\Aimage\/.*\z/
  has_attached_file :theme_song
  validates_attachment_content_type :theme_song, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
end

app/models/theme_song.rb
class ThemeSong < ApplicationRecord
  has_attached_file :audio
  validates_attachment_content_type :audio, :content_type => [ 'audio/mpeg', 'audio/x-mpeg', 'audio/mp3', 'audio/x-mp3', 'audio/mpeg3', 'audio/x-mpeg3', 'audio/mpg', 'audio/x-mpg', 'audio/x-mpegaudio' ]
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :omniauthable, omniauth_providers: %i[google_oauth2 facebook]
  has_many :events
  has_many :ads
  validates :name, :email, presence: true
  has_attached_file :avatar, styles: { medium: '300x300>', thumb: '100x100>' }, default_url: '/images/:style/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      user = User.create!(
        name: auth.info.name,
        provider: auth.provider,
        uid: auth.uid,
        email: auth.info.email,
        password: Devise.friendly_token[0, 20]
      )
      if auth.info.image.present?
        avatar_url = process_uri(auth.info.image)
        user.update_attribute(:avatar, URI.parse(avatar_url))
        return user
      end
    end
  end

  private

  def self.process_uri(uri)
    require 'open-uri'
    require 'open_uri_redirections'
    open(uri, allow_redirections: :safe) do |r|
      r.base_uri.to_s
    end
  end
end

app/controllers/ads_controller.rb
class AdsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :find_ad, only: %i[show edit destroy update]
  before_action :find_event, only: %i[show new create destroy edit update]
  before_action :find_user, only: %i[new create edit update destroy]

  def new
    @ad = @event.ads.new
  end

  def create
    @ad = @event.ads.new ad_params
    if @ad.save
      DeleteAdWorker.perform_at(@ad.termination_date + 1.day, @ad.id)
      redirect_to [@event, @ad], notice: 'Your ad was successfully created.'
    else
      render :new, notice: 'Something went wrong. Please try again.'
    end
  end

  def show; end

  def update
    if @event.ads.update(ad_params)
      redirect_to [@event, @ad], notice: 'Your ad was successfully updated.'
    end
  end

  def edit; end

  def destroy
    @ad.destroy
    redirect_to event_path(@event), notice: 'Your ad was successfully destroyed.'
  end

  private

  def find_event
    @event = Event.friendly.find(params[:event_id])
  rescue ActiveRecord::RecordNotFound
    render 'errors/not_found', status: :not_found
  end

  def ad_params
    params.require(:ad).permit(:title, :description, :start_date, :termination_date, :file, :slug).merge(event_id: @event.id, user_id: @user)
  end

  def find_user
    @user = current_user.id
  end

  def find_ad
    @ad = Ad.friendly.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :redirect_to_https
  before_action :configure_permitted_parameters, if: :devise_controller?
  protect_from_forgery with: :null_session

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password about locale avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name about locale avatar])
  end

  def redirect_to_https
    redirect_to protocol: 'https://' unless request.ssl? || request.local?
  end
end

app/controllers/auth_controller.rb
class AuthController < ApplicationController
  def is_signed_in?
    if user_signed_in?
      render json: { 'signed_in' => true, 'user' => current_user }.to_json
    else
      render json: { 'signed_in' => false }.to_json
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: %i[new create edit update destroy]
  before_action :set_user, only: %i[new create edit update destroy]
  before_action :find_event, only: %i[show edit update destroy]

  def index
    @events = SearchesEvents.new(query: params[:q]).call
  end

  def show
    @ads = @event.ads
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      DeleteEventWorker.perform_at(@event.termination_date + 1.day, @event.id)
      redirect_to event_path(@event), notice: 'Your event was successfully created.'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @event.update(event_params)
      redirect_to event_path(@event), notice: 'Your event was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Your event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def find_event
    @event = Event.friendly.find(params[:id])
  end

  def set_user
    @user = current_user.id
  end

  def event_params
    params.require(:event).permit(:title, :description, :start_date, :termination_date, :file, :address, :radius, :slug, :theme_song).merge(user_id: @user)
  end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
    @hello_world_props = { name: 'Stranger' }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/passwords_controller.rb
class PasswordsController < Devise::PasswordsController
  def edit
    self.resource = resource_class.find_or_initialize_with_error_by(:reset_password_token, params[:reset_password_token])
    if !resource.errors.empty?
      flash[:alert] = "Password token is invalid"
      redirect_to new_session_path(resource_name)
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def self.provides_callback_for(provider)
    class_eval %{
    def #{provider}
        @user = User.from_omniauth(request.env['omniauth.auth'])
        if @user.persisted?
          set_flash_message(:notice, :success, kind: "#{provider}".capitalize) if is_navigational_format?
          sign_in_and_redirect @user, event: :authentication
        else
          session["devise.#{provider}_data"] = env["omniauth.auth"]
          redirect_to new_user_registration_url, notice: 'Authentication was unsuccessful.'
        end
      end
  }
  end

  %i[facebook google_oauth2].each do |provider|
    provides_callback_for provider
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end
end

app/helpers/ads_helper.rb
module AdsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/passwords_helper.rb
module PasswordsHelper
end

app/views/ads/_disqus.html.erb
<div id="disqus_thread"></div>
<script>
  /**
  *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
  *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
  /*
  var disqus_config = function () {
  this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
  this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  };
  */
  
  var disqus_config = function () {
  this.page.url = festiswap.herokuapp.com;  // Replace PAGE_URL with your page's canonical URL variable
  this.page.identifier = '<%= @ad.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
  this.page.title = '<%= @ad.title %>';
  };
  
  (function() { // DON'T EDIT BELOW THIS LINE
  var d = document, s = d.createElement('script');
  s.src = 'https://festiswap.disqus.com/embed.js';
  s.setAttribute('data-timestamp', +new Date());
  (d.head || d.body).appendChild(s);
  })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/ads/_form.html.erb
<%= form_for([@event, @ad]) do |f| %>
  <% if @ad.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ad.errors.count, "error") %> prohibited this ad from being saved:</h2>
      <ul>
        <% @ad.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :required => true %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :required => true %>
  </div>
  <div class="field">
    <%= f.label :start_date %> <em>(This event starts on <%= @event.start_date.strftime("%d %b, %Y") %> your ad start date must match or start after this date.)</em><br />
    <%= f.datetime_local_field :start_date, class: "datepicker" %>
  </div>
  <div class="field">
    <%= f.label :termination_date %> <em>(This event ends on <%= @event.termination_date.strftime("%d %b, %Y") %> your ad end date must match or end before this date.)</em><br />
    <%= f.datetime_local_field :termination_date, class: "datepicker"  %>
  </div>
  <div class="field">
    <%= f.file_field :file %><br />
    <br />
    <%= image_tag @ad.file.url(:medium) %><br />
  </div>
  <button class="btn waves-effect waves-light" type="submit" name="action">Submit</button><br />
  <br />
<% end %>
<script>
  $('.datepicker').pickadate({
  selectMonths: true, // Creates a dropdown to control month
  selectYears: 15 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/ads/edit.html.erb
<h1>Edit Ad</h1>
<%= render 'form' %>
<div class="waves-effect waves-light btn white">
  <%= link_to 'Show', event_ad_path %> |
</div>
<div class="waves-effect waves-light btn white">
  <%= link_to 'Back', event_path(@event) %>
</div>

app/views/ads/new.html.erb
<h1>New Ad</h1>
<%= render 'form' %>
<div class="waves-effect waves-light btn white">
  <%= link_to 'Back', event_path(@event) %>
</div>

app/views/ads/show.html.erb
<div class="card hoverable">
  <h4>
    <%= @ad.title %>
    <div class="divider"></div>
    <span><%= image_tag @ad.file.url(:medium) %></span>
  </h4>
  <p>
    <b>Description:</b>
    <%= @ad.description %>
  </p>
  <p>
    <b>Dates at Event:</b>
    <%= @ad.start_date.strftime("%b %d, %Y") %> -
    <%= @ad.termination_date.strftime("%b %d, %Y") %>
  </p>
  <% if current_user %>
    <% if current_user.id == @ad.user_id %>
      <div class="waves-effect waves-light btn white">
        <%= link_to 'Edit', edit_event_ad_path(@event, @ad) %>
      </div>
      <%= link_to 'Destroy', event_ad_path(@event, @ad), :confirm => 'Are you sure?', method: :delete, class: "waves-effect waves-light btn red" %>
    <% end %>
  </td>
</td>
<% end %>
<div class="waves-effect waves-light btn white">
  <%= link_to 'Back', event_path(@event) %>
</div>
<%= render 'disqus' %>
</div>

app/views/events/edit.html.erb
<h1>Edit Event</h1>
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :required => true %><br>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, :required => true %><br>
  </div>
  <div class="field">
    <%= f.hidden_field :start_date %>
  </div>
  <div class="field">
    <%= f.hidden_field :termination_date %>
  </div>
  <div class="field">
    <%= f.file_field :file %><br />
    <br />
    <%= image_tag @event.file.url(:medium) %><br />
  </div>
  <button class="btn waves-effect waves-light" type="submit" name="action">Update</button><br/>
  <br />
<% end %>
<div class="waves-effect waves-light btn white">
  <%= link_to 'Show', @event %> |
</div>
<div class="waves-effect waves-light btn white">
  <%= link_to 'Back', events_path %>
</div>

app/views/events/index.html.erb
<script type="text/javascript">
  function initMap() {}
</script>
<script type="text/javascript">
  $(document).ready(function() {
    $('#texttohide').delay(5000).fadeOut();
  });
</script>
<p id="texttohide" class="loading">It may take a moment to obtain your current location. Please wait</p>
<h3>Your Location & Event Circles</h3>
<div class="card" style="width: auto;">
  <script type="text/javascript">
    $(document).ready(initMap());
    $(document).ready(navigator.geolocation.getCurrentPosition(locationSuccess, locationFail));
  </script>
  <div id="map" style="position: auto; overflow: auto; height: 400px; width: auto;"></div>
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['google_maps_key'] %>&callback=initMap"></script>
</div>
<table class="card table highlight bordered s10">
  <thead>
    <h3>Events</h3>
  </thead>
  <tbody>
    <% count = 0 %>
    <% @events.each do |event| %>
      <tr id="row<%= count %>" class="card hoverable">
        <div id="event<%= count %>_latitude" class="hide">
          <%= event.latitude %>
        </div>
        <div id="event<%= count %>_longitude" class="hide">
          <%= event.longitude %>
        </div>
        <div id="event<%= count %>_radius" class="hide">
          <%= event.radius %>
        </div>
        <td colspan="3">
          <a href="<%= event_path(event) %>">
            <%= image_tag event.file.url(:thumb) %>
          </a>
        </td>
        <td colspan="3">
          <a href="<%= event_path(event) %>">
            <%= event.title %>
          </a>
        </td>
        <td id="event<%= count %>_latitude">
          <a href="<%= event_path(event) %>">
            <%= event.address %>
          </a>
        </td>
        <td>
          <a href="<%= event_path(event) %>">
            <%= event.start_date.strftime("%b %d, %Y") %>
            -
            <%= event.termination_date.strftime("%b %d, %Y") %>
          </a>
        </td>
      </tr>
      <% count += 1 %>
    <% end %>
  </tbody>
</table>
<div class="waves-effect waves-light btn white">
  <%= link_to 'Back', root_path %>
</div>
<% if current_user %>
  <div class="waves-effect waves-light btn white">
    <%= link_to 'New Event', new_event_path %>
  </div>
<% end %>

app/views/events/new.html.erb
<h1>New Event</h1>
<%= form_with(model: @event, local: true, multipart: true) do |form| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>
      <ul>
        <% @event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @event, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title, :required => true %><br>
    </div>
    <div class="field">
      <%= f.label :description %><br />
      <%= f.text_area :description, :required => true %><br>
    </div>
    <div type="date" class="datepicker">
      <%= f.label :start_date %><br />
      <%= f.datetime_local_field :start_date, class: "datepicker" %>
    </div>
    <div class="field">
      <%= f.label :termination_date %><br />
      <%= f.datetime_local_field :termination_date, class: "datepicker" %>
    </div>
    <div class="field">
      <%= f.label :address %><br />
      <%= f.text_field :address, :required => true %><br>
    </div>
    <div class="field browser-default">
      <script>
        $(document).ready(function() {
          $('select').material_select();
        });
      </script>
      <%= f.label :radius %> (hundred yards)<br />
      <%= f.select :radius, [1, 2, 3, 4, 5], :required => true %>
    </div>
    <div class="field">
      <%= f.file_field :file %><br />
      <br />
      <%= image_tag @event.file.url(:medium) %><br />
      <div class="field">
        <%= f.file_field :theme_song %><br />
      <br />
      </div>
    </div>
    <button class="btn waves-effect waves-light" type="submit" name="action">Create</button><br/>
  <% end %>
<% end %>
<br />
<div class="waves-effect waves-light btn white">
  <%= link_to 'Back', events_path %>
</div>
<script>
  $('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
</script>

app/views/events/show.html.erb
<div class="card hoverable" style="width: auto;">
  <h4>
    <%= @event.title %>
    <div class="divider"></div>
    <span><%= image_tag @event.file.url(:medium) %></span>
  </h4>
  <p>
    <b>Description:</b>
    <%= @event.description %>
  </p>
  <p>
    <b>Address:</b>
    <%= @event.address %>
  </p>
  <p><b>Theme Song:</b>
  <%= @event.theme_song %>
  <div class="container">
  <%= react_component 'Audio', id: @event.theme_song, action: @event, audio: @event.theme_song %>
  </div>
  <div class="waves-effect waves-light btn white">
    <%= link_to 'Create Ad', new_event_ad_path(@event.id) %>
  </div>
  <% if current_user %>
    <% if current_user.id == @event.user_id %>
      <div class="waves-effect waves-light btn white">
        <%= link_to 'Edit Event', edit_event_path(@event) %>
      </div>
    <% end %>
  <% end %>
  <div class="waves-effect waves-light btn white">
    <%= link_to 'Back', events_path %>
  </div>
</div>
<div class="card" style="width: auto;">
  <iframe width="100%" height="350" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=<%= ENV['google_maps_key'] %>&q=<%= @event.latitude.floor(5) %>,<%= @event.longitude.floor(5) %>" allowfullscreen>
  </iframe>
</div>
<table class="card table col s12 m8">
  <thead>
    <h3>
      Ads
    </h3>
  </thead>
  <tbody>
    <% @ads.map do |ad| %>
      <tr class="card hoverable">
        <td colspan="3">
          <img alt="" class="circle responsive-img">
          <a href="<%= event_ad_path(@event, ad) %>">
            <%= image_tag ad.file.url(:thumb) %>
          </a>
        </img>
      </td>
      <td colspan="3">
        <a href="<%= event_ad_path(@event, ad) %>">
          <%= ad.title %>
        </a>
      </td>
      <td class="hide-on-med-and-down" colspan="3">
        <div class="hide-on-med-and-down">
          <a href="<%= event_ad_path(@event, ad) %>">
            <%= ad.description %>
          </a>
        </div>
      </td>
      <td>
        <a href="<%= event_ad_path(@event, ad) %>">
          <%= ad.start_date.strftime("%b %d, %Y") %>
          -
          <%= ad.termination_date.strftime("%b %d, %Y") %>
          <a href="<%= event_ad_path(@event, ad) %>">
          </td>
          <% if current_user %>
            <% if current_user.id == ad.user_id %>
              <td>
                <%= link_to 'Edit', edit_event_ad_path(ad.event, ad) %>
              </td>
              <td>
                <%= link_to 'Destroy', event_ad_path(ad.event, ad), :confirm => 'Are you sure?', :method => :delete %>
              </td>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/hello_world/index.html.erb
<h1>Hello World</h1>
<%= react_component("HelloWorld", props: @hello_world_props, prerender: false) %>

app/views/home/index.html.erb
<div class="s12 m11">
  <h1>Welcome to FestiSwap </h1>
  <h2>The Marketplace, for time and space...</h2>
  <%= link_to 'Find Events', events_path, class: "waves-effect waves-light btn" %>
  <%= link_to 'Create Event', new_event_path, class: "waves-effect waves-light btn" %>
  <h3>FestiSwap is a classifieds app for events.</h3>
  <h4>You can search for events by:</h4>
  <li>Entering a location in the search bar or...</li>
  <li>Clicking on the find events button</li>
  <em>MAKE SURE YOU HIT <strong>YES</strong> or <strong>ACCEPT</strong> WHEN YOU ARE PROMPTED FOR LOCATION PERMISSIONS</em>
  <h4>You can create your own events by:</h4>
  <li>Registering or Logging In</li>
  <li>Hitting the <em>Create Event</em> button on the home page or at the bottom of the event listing pages</li>
  <h4>You can create your own ads by:</h4>
  <li>Registering or Logging In</li>
  <li>Navigating to an events page</li>
  <li>Hitting the <em>Create Ad</em> button at the bottom of the event's page</li>
</div>

app/views/layouts/_footer.html.erb
<footer class="page-footer #424242 grey darken-3 z-depth-5">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <p class="grey-text text-lighten-4">This website was created by students of <a class="grey-text text-lighten-4" href="http://www.codeplatoon.org/">Code Platoon.</a></p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2017 Copyright Text
      <a class="grey-text text-lighten-4 right" href="https://github.com/iamretiform/FestiSwap">GitHub Repository</a>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav>
  <div class="nav-wrapper #424242 grey darken-3 z-depth-5">
    <a href="/" class="brand-logo">
      <text class="hide-on-med-and-down">FestiSwap</text><i class="btn icons left z-depth-6"><img height="55" width="55" src="https://s3.us-east-2.amazonaws.com/festiswap/system/images/app_images/whtfestsw.png"></i></a>
  </div>
</nav>
<div class="row">
  <div class="container s12 m10 l10">
    <% if current_user %>
      <div class="card nav-wrapper" height="150px">
        <div class="avatar valign-wrapper">
          <image class="circle" src="<%= current_user.avatar.url(:thumb) %>"></image>
          <span class="title">Welcome <%= current_user.name %>!</span>
          <br>
          <div class="col s0 m4 l4"></div>
          <div class="secondary-content">
            <a class="btn btn-floating cyan waves-effect waves-light hoverable" href="<%= edit_user_registration_path %>">
              <i class="material-icons">edit</i>
              <a class="hide-on-med-and-down" href="<%= edit_user_registration_path %>">
                <%= link_to ' Edit Account', edit_user_registration_path %>
              </a>
            </a>
            <a class="btn btn-floating red waves-effect waves-light hoverable" data-method="delete" href="<%= destroy_user_session_path %>">
              <i class="material-icons">settings_power</i>
              <%= link_to ' Logout', destroy_user_session_path, method: :delete %>
            </a>
          <% else %>
            <div class="collection" height="150px">
              <div class="collection-item #4BB8A6FF teal lighten-2">
                <div class="waves-effect waves-light btn white">
                  <%= link_to 'Register',new_user_registration_path %>
                </div>
              </div>
              <div class="collection-item #4BB8A6FF teal lighten-2">
                <div class="waves-effect waves-light btn white">
                  <%= link_to 'Login', new_user_session_path %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="container grid-example col s12 m5">
  <nav>
    <div class="collection nav-wrapper">
      <form role="search" action="/events">
        <span class="flow-text">
          <div class="input-field #4BB8A6FF teal lighten-2 truncate">
            <input type="text" name="q" placeholder="Enter a location to find its nearby events..." id="search" type="search" required>
            <label class="label-icon" for="search"><i class="material-icons">search</i></label>
          </div>
        </span>
      </form>
    </div>
  </nav>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <!-- googly icon fonts -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!-- materialize css biblioteca -->
    <!-- makes for mobile devices -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>FestiSwap</title>
    <link rel="icon" href="https://s3.us-east-2.amazonaws.com/festiswap/system/images/app_images/whtfestsw.png" type="image/gif" />
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container s12 m10 l10">
      <% flash.each do |key, value| %>
        <div id="texttohide" class="alert alert-<%= key %>">
          <br />
          <%= value %>
        </div>
      <% end %>
      <%= yield %>
    </div>
    <br />
    <%= render 'layouts/footer' %>
    <script type="text/javascript">
      $(document).ready(function() {
      $('#texttohide').delay(5000).fadeOut();
      });
    </script>
  </body>
</html>